root_folder: ./data
method: hoc

# iamcl2r settings
pretrained_model_path: 
- ./pretrained_models_ckpts/learnable/ckpt_0.pt
- ./pretrained_models_ckpts/learnable/ckpt_2.pt
pretrained_backbones: 
- resnet18
- resnet18
replace_ids: 
- 1

increment: 50
initial_increment: 50

# for hoc
fixed: true
preallocated_classes: 1024
mu_: 10
lambda_: 0.1
# epochs: 3
