root_folder: ./data
method: er

# iamcl2r settings
pretrained_model_path: 
- torchvision_pretrained
- torchvision_pretrained
- torchvision_pretrained
pretrained_backbones:
- resnet18_torchvision
- resnet50_torchvision
- resnet101_torchvision
replace_ids: 
- 2
- 4
# training settings
scenario: 'class-incremental'
increment: 15
train_dataset_name: 'cifar_clr'
batch_size: 256
lr: 0.002
momentum: 0.9
min_lr: 0.00001
weight_decay: 0.0005
epochs: 100
rehearsal: 20
fixed: false
