root_folder: ./data
method: clr_hoc

# iamcl2r settings
pretrained_model_path: 
- pretrained_models_ckpts/learnable/ckpt_0.pt
- pretrained_models_ckpts/learnable/ckpt_1.pt
- pretrained_models_ckpts/learnable/ckpt_2.pt
pretrained_backbones:
- resnet18
- resnet18
- resnet18
replace_ids: 
- 2
- 4
# training settings
scenario: 'instance-incremental'
feat_size: null
nb_tasks: 7
train_dataset_name: 'cifar_clr'
batch_size: 256
lr: 0.003
momentum: 0.9
min_lr: 0.00001
weight_decay: 0.0005
epochs: 100
rehearsal: 200
