root_folder: ./data
method: er

# iamcl2r settings
pretrained_model_path: 
- torchvision_pretrained
- torchvision_pretrained
- torchvision_pretrained
pretrained_backbones:
- resnet18_torchvision
- resnet50_torchvision
- resnet101_torchvision
replace_ids: 
- 1
- 2

# checkpoint_path: ./models_ckpts/er_3tasks_arch/run-20240721-0611
# eval_only: True
# training settings
scenario: 'instance-incremental'
nb_tasks: 3
rehersal: 300

batch_size: 512
# backbone_lr: 0.0001
# lr: 0.001
# grad_clip: 0.01
# momentum: 0.9
# min_lr: 0.00001
# weight_decay: 0.001
epochs: 100
